### ISSUE TITLE
Compile error on Ubuntu 14.04

### ISSUE THREAD

**Issue by parnold-x** [Kekun/retro-gtk#4]
Hi when compiling i get the this error:
RetroGtk-0.1.gir:In InputDeviceManager: error: Can't resolve type 'Retro.InputDeviceManager' for field RetroGtk.InputDeviceManager.parent_instance
http://pastebin.com/k7N314hy

It seems like all the other retro deps could be found so the dependency to retro-gobject should be ok?!
Any hint?

**Comment by Kekun** [comment]
Thanks, I just installed Ubuntu 14.04 on a VM to check that, I'll try to reproduce and fix it this WE.

**Comment by retsef** [comment]
I have solved this by putting in [Retro.vala] (https://github.com/Kekun/retro-gobject/blob/master/retro/Retro.vala) after Retro namespace this line 
` [CCode (gir_namespace = "Retro", gir_version = "0.2")]  `

**Comment by parnold-x** [comment]
Nice, thx. Was also able to compile it with that.
Btw. great work Kekun!

**Comment by Kekun** [comment]
Thanks a lot retsef, this one was sneaky!
